fulcrumgenomics/prymer

- poetry.lock
- prymer/offtarget/offtarget_detector.py
- tests/offtarget/test_offtarget.py
> feat: Make `OffTargetDetector.filter()` generic

- .github/workflows/publish_prymer.yml
- README.md
Closes: https://github.com/fulcrumgenomics/prymer/issues/3
Closes: https://github.com/fulcrumgenomics/prymer/issues/24
And the updated PyPi trusted publisher config:
> chore: fix PyPi trusted publishing in GitHub Actions

- prymer/primer3/primer3.py
- prymer/primer3/primer3_parameters.py
- tests/primer3/test_primer3.py
Closes #16 
Closes #17 
This PR fixes the padding of the target region to be consistent with the original `fgprimer` implementation. (My bad 🙃 )
https://github.com/fulcrumgenomics/fgprimer/blob/6cf2542e927ced37dd0dce4c335de8dff07789c7/src/main/scala/com/fulcrumgenomics/primerdesign/primer3/Primer3.scala#L89-L93
Other changes
- Validate that the max amplicon length permits sufficient space around the target region for primers to be designed
- Renamed `region` to `design_region`, to better reflect the target/design region distinction
- Renamed `_pad_target_region` to `_create_design_region`, for the same reason, and clarified its documentation
- Added `min_primer_length` property to `Primer3Parameters` (`max_primer_length` already existed)
> fix: Pad target region by `max_amplicon_length`

- tests/util/test_executable_runner.py
Closes #20 
Homebrew installation of the GNU coreutils caused a conflict with expectation in the `ExecutableRunner` validation tests.
Tests were updated to clear the `PATH` before executing.
> fix: Executable path validation tests should not be dependent on the user environment

- prymer/offtarget/offtarget_detector.py
Closes #43 
This PR introduces a new parameter to `OffTargetDetector`, `min_primer_pair_hits`. This permits the user to relax the current constraint that every primer pair have at least one hit in the reference. 
I have set the default value to 1, so default behavior remains unchanged by this PR, and documented the use case where it may be appropriate to change this value.
> feat: Add support for `min_primer_pair_hits` to `OffTargetDetector` 

- prymer/api/picking.py
- prymer/offtarget/__init__.py
- tests/api/test_picking.py
- tests/offtarget/test_offtarget.py
This should be in the `offtarget` namespace if `OffTargetResult` is
> refactor: export OffTargetDetector

- prymer/offtarget/offtarget_detector.py
I added documentation to explain how the class can be used to filter primers vs primer pairs, and the behavior of each filtering method. 
I also added `Args` and `Return` blocks to the public methods.
> doc: Expand the documentation for `OffTargetDetector`

- prymer/primer3/primer3.py
- prymer/primer3/primer3_input.py
- prymer/primer3/primer3_parameters.py
- tests/primer3/test_primer3.py
- tests/primer3/test_primer3_parameters.py
- tests/primer3/test_primer3_weights.py
* Refactor original `Primer3Parameters` to now be called `PrimerAndAmpliconParameters`
* Add `DeprecationWarning` to `Primer3Parameters` for backwards compatibility
* Add `ProbeParameters` to encapsulate settings for `PickHybProbeOnly` Primer3Task, as well as a `post_init()` and `to_input_tags()` that maps each of the user-specified arguments to the corresponding `Primer3InputTag`
* Make `*_params` and `*_weights` both optional input to `Primer3Input`, use the `__post_init()__` to assign default weights when given the corresponding params
> feat: add `ProbeParameters()` to encapsulate settings for `PickHybProbeOnly` Primer3Task

- .github/workflows/tests.yml
- prymer/offtarget/bwa.py
- tests/offtarget/test_bwa.py
It is mentioned `pysam.AlignmentFile` internally buffers stdin so a hack was devised to "warm it up".
However, `fgpyo.sam.reader` and `pysam.AlignmentFile` are actually not needed and only provide code indirection since we can build the SAM header and all subsequent records using the [`from_text()`](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentHeader.from_text)/[`fromstring()`](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.fromstring) methods of each.
> feat: remove pysam and bwa warmup hack

- prymer/primer3/__init__.py
So the task can be imported from `prymer.primer3` like the other tasks.
@tfenne I should have thought of this while we were discussing #51, but do you have any thoughts on whether this task might be renamed for consistency with the other tasks and ease of discovery? e.g. `PickHybProbeOnlyTask`, or `DesignProbeTask`
> chore: export PickHybProbeOnly task

- prymer/offtarget/bwa.py
- tests/offtarget/test_bwa.py
Closes #68 
`bwa aln` produces inconsistent behavior when recording the mapped status of multiply mapping reads. In most cases, such reads are flagged as mapped with a mapq of 0. However, we have discovered some cases where these reads are flagged as unmapped. 
`prymer` currently relies on the unmapped flag to identify reads with a hit count of zero. This has been yielding errors when attempting to parse reads in the latter category. This information can instead be obtained directly from the `HN` tag.
---
NB: Thanks to detective work by @tfenne 
> This happens because internally bwa concatenates all the sequences in the FASTA file, so it can discover hits that extend across contig boundaries.  Unfortunately when it discovers it’s done this on the mapping selected as the primary mapping, …
> fix: Check against `HN` tag instead of `is_unmapped` property

- prymer/offtarget/bwa.py
- prymer/util/executable_runner.py
- tests/offtarget/test_bwa.py
This doesn't fully close:
- https://github.com/fulcrumgenomics/prymer/issues/41
But it does redirect the stderr stream to a debug logger.
Users of this library can override the logging level of all loggers/handles to be able to view these log messages if they choose, but a convenient way to change the logging levels within prymer does not yet exist and could be implemented in a future PR.
> feat: redirect BwaAlnInteractive stderr to debug logging

- docs/overview.md
- prymer/api/__init__.py
- prymer/api/picking.py
- tests/api/test_picking.py
Closes https://github.com/fulcrumgenomics/prymer/issues/38
> Reducing `picking.py` to be simpler, more focused, and more performant.

- .gitignore
- prymer/api/picking.py
> Use Sequence instead of list[] in parameters to build_primer_pairs()

- prymer/api/picking.py
- prymer/api/variant_lookup.py
- prymer/primer3/primer3.py
- prymer/primer3/primer3_failure_reason.py
- prymer/util/executable_runner.py
This small PR ensures that anywhere that `prymer` logs it first gets a logger via `logging.getLogger(__name__)`, rather than just doing `logging.debug(....)`.
The problem with `logging.debug()` (and similar methods directly on the logging module) is that they are side-effecting on the logging configuration.  E.g. here's the `debug()` function in `logging`:
```python
def debug(msg, *args, **kwargs):
"""
Log a message with severity 'DEBUG' on the root logger. If the logger has
no handlers, call basicConfig() to add a console handler with a pre-defined
format.
"""
if len(root.handlers) == 0:
basicConfig()
root.debug(msg, *args, **kwargs)
```
This was causing me issues in a repo that uses `prymer`, where after the first one of these calls, I then received duplicate log messages for every …
> Make sure logger.getLogger() is used instead of logging directly via logging.debug()

- prymer/api/primer_pair.py
- pyproject.toml
See this discussion for context: https://github.com/fulcrumgenomics/prymer/pull/89#discussion_r1847087921
This PR also updates the mypy config to exclude the `mkdocs` directories.
> refactor: Make `PrimerPair.amplicon` a cached property

- poetry.lock
- pyproject.toml
Does `fgpyo` need to be pinned to `0.7.1`, or can we use our usual [caret dependency](https://python-poetry.org/docs/dependency-specification/#caret-requirements) to permit any `0.x` minor version at 0.8 or later? 
I'd at least like to bump the version to 0.8.0 - it'd be helpful in a client project to have `fgpyo.io.assert_fasta_indexed()` available, which was added in 0.8.0.
> chore: unpin fgpyo dependency

- poetry.lock
- pyproject.toml
Similar to #97 , this PR unpins the dependency on pybedlite.
I am opening two separate PRs in case there is an argument for one dependency to be pinned but not the other.
> chore: unpin pybedlite dependency

- prymer/api/picking.py
- tests/api/test_picking.py
This PR does two things:
1. Fix a bug where amplicons that were too _small_ were still emitted
2. Ensure that primer pairs are emitted in penalty order
(2) requires materializing a small tuple for all _valid_ pairs, and then sorting by score.  The tuple contains two ints (indices into the primer sequences) and two floats (the penalty and the tm, the last for convenience so we don't have to recompute it).  It the sorts the tuples by penalty, and starts generating PrimerPairs in penalty order.
If you have e.g. 500 left and 500 right primers, this could construct ~250k tuples and calculate 250k Tms, but in reality the number is probably substantially smaller constrained by amplicon sizes.
> Emit primer pairs in penalty order.

- prymer/offtarget/bwa.py
- prymer/offtarget/offtarget_detector.py
- tests/offtarget/test_bwa.py
I did some playing with ntthal, and it appears to that the when calculating Tms of duplexes, an indel closer than 3bp from the end of the primer causes it to see the rest of the primer as non-annealed.  In some cases it can be more (depending on sequence, it may not see the remainder as annealed after an indel 4-5bp in), but it seems consistent that it needs _at least_ 3bp past the indel to anneal bases.  Hence setting `min_indel_to_end_distance: int = 3`.
> Expose some bwa indel parameters through the off-target checker.

- prymer/offtarget/offtarget_detector.py
- tests/offtarget/test_offtarget.py
Closes #94 
1. `OffTargetDetector._to_amplicons` signature changes from 
```
def _to_amplicons(lefts: list[BwaHit], rights: list[BwaHit], max_len: int) -> list[Span]:
```
to
```
def _to_amplicons(
positive_hits: list[BwaHit], negative_hits: list[BwaHit], max_len: int, strand: Strand
) -> list[Span]:
```
- Amplicons are built from a list of single primer hits on the positive strand and a list of single primer hits on the negative strand.
- New parameter `strand` is used to set the `strand` attribute on each of the returned `Span`s for the amplicon hits. 
- Validates that all positive hits are on the positive strand and all negative hits are on the negative strand.
- Validates that all hits are on the same reference (e.g. contig/chr).
2. The existing unit test for …
> feat: speed improvements for primer pair hit building from single primer hits

- prymer/offtarget/offtarget_detector.py
- tests/offtarget/test_offtarget.py
- `max_amplicon_size > 0`
- `max_primer_hits >= 0`
- `max_primer_pair_hits >= 0`
- `min_primer_pair_hits >= 0`
- `three_prime_region_length > 0`
- `0 <= max_mismatches_in_three_prime_region <= three_prime_region_length`
- `max_mismatches >= 0`
- `max_gap_opens >= 0`
- `max_gap_extends == -1` or `max_gap_extends >= 0`
> feat: Add parameter validation for `OffTargetDetector.__init__`
